spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.8.131:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
mybatis:
  type-aliases-package: com.example.demo.dao
  mapper-locations: classpath:mapper/*Mapper.xml


